name: remote ssh command
on: [push]
jobs:

  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: pull and build via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd documents/mk3-core
            git pull
            npm install
            npm run build
            pm2 restart server
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          pass: ${{ secrets.DEPLOY_PASSWORD }}
